on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://waws-prod-blu-165dr.ftp.azurewebsites.windows.net/site/wwwroot
        ftp-username: WVUP-CollegeQuest\$WVUP-CollegeQuest
        ftp-password: ${{ secrets.KdEfknzK2MaTbvMMA9kqAvroWdqW70XHd9Hlpw5LkbSX7Sjo96x8zfWA1TL0}}
	local-dir: Build/Build/
	Build/TemplateData/
	Build/index.html