on: push
name: Push Unity Build to Azure
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
        
    - name: List output files
      run: ls
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftps://waws-prod-blu-165.ftp.azurewebsites.windows.net/site/wwwroot
        ftp-username: WVUP-CollegeQuest\$WVUP-CollegeQuest
        ftp-password: KdEfknzK2MaTbvMMA9kqAvroWdqW70XHd9Hlpw5LkbSX7Sjo96x8zfWA1TL0
        local-dir: WVUP-TheCollegeQuest/Build/
